name = "ExploreCraft: Marbled"
author = "Sangelo"
version = "2.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec012f31bb1fa40d5852f75408307d70f85d67dde3b5af084abbda1e8d095b83"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
