name = "ExploreCraft: Marbled"
author = "Sangelo"
version = "2.0_Pre-Release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4047f0a5af51576407ca01d84536ba00dadd0ea64b28cdbd3ed5b6754161ccba"

[versions]
minecraft = "1.19.2"
quilt = "0.18.9"
