name = "ExploreCraft: Marbled"
author = "Sangelo"
version = "2.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c4b7e5557d5beec1f956acd1d158c59c479776f6b0319c8af0a5e83f99f7cfb"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
