name = "ExploreCraft: Marbled"
author = "Sangelo"
version = "2.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "153cc0c35ce5caee384ecea00ed3429437726970d4028995fae87bd44781ce66"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
