name = "ExploreCraft"
author = "Sangelo"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31bc55fd1ad80e087751b78139481607448b161451213004fdde098a7447a796"

[versions]
minecraft = "1.19"
quilt = "0.17.3"
