name = "ExploreCraft: Marbled"
author = "Sangelo"
version = "2.0_Pre-Release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52ef730a5905feaaeb5f9bd5b88c3999aa0bc6b43c56d43142388d31ea958c75"

[versions]
minecraft = "1.19.2"
quilt = "0.18.9"
