name = "ExploreCraft: Marbled"
author = "Sangelo"
version = "2.0_Pre-Release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bd16753c96b77d7554e4e4e512607d78fb6e86ebe4d37ad6423dc51b78ab301"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
