name = "ExploreCraft: Marbled"
author = "Sangelo"
version = "2.0_Pre-Release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcebba094e64a358b9f6bdfaa0f4524837fd71ff7776375bc1bf27c7fa2f829b"

[versions]
minecraft = "1.19.2"
quilt = "0.18.3"
