name = "ExploreCraft"
author = "Sangelo"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ab14c483b1b8363125b660c64b41b15d31c2e30cb5098593e4f498c41035151"

[versions]
minecraft = "1.19"
quilt = "0.17.3"
