name = "ExploreCraft: Marbled"
author = "Sangelo"
version = "2.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cae6f8c40e7d7dfb934957ff65826c78be308e4ab42ec1b5dfdabf29e662d43d"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
