name = "ExploreCraft: Marbled"
author = "Sangelo"
version = "2.0_Pre-Release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "680f76a18204e2f093cc9b21840835a60b840343bb177395cc3ea7ad27be7b0c"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
