name = "ExploreCraft: Marbled"
author = "Sangelo"
version = "2.0_Pre-Release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "267a9943c27d769bc216de40058807e7b0f17dc84d0220ea5c0f77c9f1365c45"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
