name = "ExploreCraft: Marbled"
author = "Sangelo"
version = "2.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "037eb66665c5dbf8b6372f084606b3669938e0991ec034858ed6dcb3de3f0d3d"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
