name = "ExploreCraft"
author = "Sangelo"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc569ef5649348169030a49c6b3a43108129ec2e3a97e55744a34a44c92d477f"

[versions]
minecraft = "1.19"
quilt = "0.17.3"
