name = "ExploreCraft: Marbled"
author = "Sangelo"
version = "2.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a09b9196930e582d696dfca57a1935d42ae0f3f60d9526f16714749150c990d5"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
