name = "ExploreCraft: Marbled"
author = "Sangelo"
version = "2.0_Pre-Release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83a9677e28e09b1db115d49bddbf9f76a9238b62cd74903770c4a42c3025437d"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
