name = "ExploreCraft: Marbled"
author = "Sangelo"
version = "2.0_Pre-Release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e45b7614f3e30356eee810290187d8ccbf3716ddb959424f4bee411ad1935aba"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
