# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "fancy"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "fancy"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				bee = true
				axolotl = true
				egg = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				bat = true
				husk = true
				frog = true
				hoglin = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wandering_trader = true
				piglin_brute = true
				goat = true
				ocelot = true
				item_frame = true
				horse = true
				ender_dragon = true
				leash_knot = true
				llama_spit = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				trader_llama = true
				donkey = true
				chest_minecart = true
				fox = true
				tropical_fish = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				piglin = true
				cat = true
				zombie = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				wolf = true
				villager = true
				zombie_villager = true
				boat = true
				strider = true
				polar_bear = true
				painting = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.levelz]
				level_experience_orb = true

			[light_sources.settings.entities.biomemakeover]
				rootling = true
				dragonfly = true
				decayed = true
				ghost = true
				scuttler = true
				owl = true
				moth = true
				lightning_bottle = true
				helmit_crab = true
				tumbleweed = true

			[light_sources.settings.entities.fishofthieves]
				devilfish = true
				splashtail = true
				stormfish = true
				ancientscale = true
				wrecker = true
				wildsplash = true
				plentifin = true
				islehopper = true
				pondie = true

			[light_sources.settings.entities.adorn]
				seat = true

			[light_sources.settings.entities.impaled]
				atlan = true

			[light_sources.settings.entities.immersive_portals]
				nether_portal_new = true
				end_portal = true
				loading_indicator = true
				portal = true

			[light_sources.settings.entities.pickyourpoison]
				poison_dart_frog = true

			[light_sources.settings.entities.mythicmounts]
				firebird = true
				courierbird = true
				dragon = true
				griffon = true
				acencia = true
				geckotoalizard = true

			[light_sources.settings.entities.capybara]
				capybara = true

			[light_sources.settings.entities.betternether]
				naga_projectile = true
				firefly = true
				flying_pig = true
				hydrogen_jellyfish = true
				skull = true
				jungle_skeleton = true
				naga = true

			[light_sources.settings.entities.adventurez]
				deer = true
				orc = true
				desert_rhino = true
				iguana = true
				amethyst_golem = true
				soul_reaper = true
				enderwarthog = true
				ender_whale = true
				summoner = true
				nightmare = true

			[light_sources.settings.entities.edenring]
				diskwing = true
				lightning_ray = true

			[light_sources.settings.entities.friendsandfoes]
				mauler = true

